/* negaflow site generator
 *
 * index.html is the template and, at the same time, the English page.
 * For every other language it writes a prerendered copy under /<lang>/ so that
 * search engines see real translated markup instead of text that only appears
 * after i18n.js runs.
 *
 *   node tools/build.mjs           write the generated files
 *   node tools/build.mjs --check   fail if the generated files are stale
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/* Change this one line when the site moves to its own domain. */
const ORIGIN = 'https://habinsong.github.io';
const BASE_PATH = '/negaflow-site';
const SITE = ORIGIN + BASE_PATH;

const DEFAULT_LANG = 'en';
const LANGS = ['en', 'ko', 'ja', 'zh', 'fr', 'de'];

/* Ownership tokens from the search consoles. Paste the value only — the part
 * inside content="…" — and leave a string empty to drop its tag.
 *   google  Google Search Console  https://search.google.com/search-console
 *   bing    Bing Webmaster Tools   https://www.bing.com/webmasters
 *   naver   네이버 서치어드바이저    https://searchadvisor.naver.com
 */
const VERIFICATION = {
  google: '',
  bing: '',
  naver: ''
};

const HREFLANG = { en: 'en', ko: 'ko', ja: 'ja', zh: 'zh-Hans', fr: 'fr', de: 'de' };
const OG_LOCALE = { en: 'en_US', ko: 'ko_KR', ja: 'ja_JP', zh: 'zh_CN', fr: 'fr_FR', de: 'de_DE' };

const HEAD_START = '<!-- nf:head:start — generated by tools/build.mjs, do not edit by hand -->';
const HEAD_END = '<!-- nf:head:end -->';

const check = process.argv.includes('--check');
const written = [];
const stale = [];

/* ── i18n dictionary ──────────────────────────────────────────────────── */

function loadDict() {
  const src = readFileSync(join(ROOT, 'assets/js/i18n.js'), 'utf8');
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(src, sandbox, { filename: 'i18n.js' });
  const dict = sandbox.window.NF_I18N;
  if (!dict) throw new Error('i18n.js did not define window.NF_I18N');
  for (const lang of LANGS) {
    if (!dict[lang]) throw new Error(`i18n.js has no "${lang}" dictionary`);
  }
  return dict;
}

/* ── template rewriting ───────────────────────────────────────────────── */

const VOID = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
  'link', 'meta', 'param', 'source', 'track', 'wbr']);

/* End of the open tag that starts at `lt`, skipping `>` inside attributes. */
function openTagEnd(html, lt) {
  let quote = null;
  for (let i = lt + 1; i < html.length; i++) {
    const c = html[i];
    if (quote) {
      if (c === quote) quote = null;
    } else if (c === '"' || c === "'") {
      quote = c;
    } else if (c === '>') {
      return i;
    }
  }
  return -1;
}

/* Start of the matching close tag for an element of `name` opened at `from`. */
function closeTagStart(html, name, from) {
  const open = new RegExp(`<${name}(?=[\\s/>])`, 'gi');
  const close = new RegExp(`</${name}\\s*>`, 'gi');
  let depth = 1;
  let i = from;
  while (i < html.length) {
    open.lastIndex = i;
    close.lastIndex = i;
    const o = open.exec(html);
    const c = close.exec(html);
    if (!c) return -1;
    if (o && o.index < c.index) {
      depth++;
      i = o.index + o[0].length;
      continue;
    }
    depth--;
    if (depth === 0) return c.index;
    i = c.index + c[0].length;
  }
  return -1;
}

/* Replace the inner markup of every [data-i18n] element with its translation. */
function applyDict(html, dict) {
  const attr = /data-i18n="([^"]+)"/g;
  const edits = [];
  let m;
  while ((m = attr.exec(html))) {
    const key = m[1];
    const value = dict[key];
    if (value == null) continue;

    const lt = html.lastIndexOf('<', m.index);
    if (lt < 0) continue;
    const name = (html.slice(lt + 1).match(/^[a-zA-Z][a-zA-Z0-9-]*/) || [])[0];
    if (!name || VOID.has(name.toLowerCase())) continue;

    const gt = openTagEnd(html, lt);
    if (gt < 0 || html[gt - 1] === '/') continue;
    const end = closeTagStart(html, name, gt + 1);
    if (end < 0) continue;

    edits.push({ start: gt + 1, end, value });
  }

  let out = html;
  for (const e of edits.reverse()) out = out.slice(0, e.start) + e.value + out.slice(e.end);
  return out;
}

function stripTags(s) {
  return String(s)
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&middot;/g, '·')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

function pageUrl(lang) {
  return lang === DEFAULT_LANG ? `${SITE}/` : `${SITE}/${lang}/`;
}

/* ── structured data ──────────────────────────────────────────────────── */

function jsonLd(lang, dict, version) {
  const app = {
    '@type': 'SoftwareApplication',
    '@id': `${SITE}/#app`,
    name: 'negaflow',
    url: pageUrl(lang),
    inLanguage: HREFLANG[lang],
    description: stripTags(dict['doc.desc']),
    applicationCategory: 'MultimediaApplication',
    applicationSubCategory: 'Photo editing',
    operatingSystem: 'macOS 14.0 or later',
    processorRequirements: 'Apple Silicon or Intel',
    softwareVersion: version,
    downloadUrl: 'https://github.com/habinsong/negaflow/releases',
    installUrl: 'https://github.com/habinsong/negaflow/releases',
    softwareHelp: 'https://github.com/habinsong/negaflow#readme',
    license: 'https://www.apache.org/licenses/LICENSE-2.0',
    isAccessibleForFree: true,
    image: `${SITE}/assets/og-image.png`,
    screenshot: `${SITE}/assets/og-image.png`,
    author: { '@type': 'Person', name: 'habin song', url: 'https://github.com/habinsong' },
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    featureList: [1, 2, 3, 4, 5, 6]
      .map((n) => dict[`feat.${n}`])
      .filter(Boolean)
      .map(stripTags)
  };

  const faq = [];
  for (let n = 1; n <= 20; n++) {
    const q = dict[`faq.q${n}`];
    const a = dict[`faq.a${n}`];
    if (!q || !a) continue;
    faq.push({
      '@type': 'Question',
      name: stripTags(q),
      acceptedAnswer: { '@type': 'Answer', text: stripTags(a) }
    });
  }

  const graph = [app];
  if (faq.length) {
    graph.push({
      '@type': 'FAQPage',
      '@id': `${pageUrl(lang)}#faq`,
      inLanguage: HREFLANG[lang],
      mainEntity: faq
    });
  }

  return JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 2);
}

/* ── head ─────────────────────────────────────────────────────────────── */

function escapeAttr(s) {
  return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

function buildHead(lang, dict, version) {
  const title = stripTags(dict['doc.title']);
  const desc = stripTags(dict['doc.desc']);
  const url = pageUrl(lang);
  const og = `${SITE}/assets/og-image.png`;

  const alternates = LANGS
    .map((l) => `<link rel="alternate" hreflang="${HREFLANG[l]}" href="${pageUrl(l)}">`)
    .concat(`<link rel="alternate" hreflang="x-default" href="${pageUrl(DEFAULT_LANG)}">`)
    .join('\n');

  return [
    HEAD_START,
    `<title>${escapeAttr(title)}</title>`,
    `<meta name="description" content="${escapeAttr(desc)}">`,
    '<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">',
    ...(VERIFICATION.google
      ? [`<meta name="google-site-verification" content="${escapeAttr(VERIFICATION.google)}">`] : []),
    ...(VERIFICATION.bing
      ? [`<meta name="msvalidate.01" content="${escapeAttr(VERIFICATION.bing)}">`] : []),
    ...(VERIFICATION.naver
      ? [`<meta name="naver-site-verification" content="${escapeAttr(VERIFICATION.naver)}">`] : []),
    `<link rel="canonical" href="${url}">`,
    alternates,
    '<meta property="og:type" content="website">',
    '<meta property="og:site_name" content="negaflow">',
    `<meta property="og:locale" content="${OG_LOCALE[lang]}">`,
    ...LANGS.filter((l) => l !== lang)
      .map((l) => `<meta property="og:locale:alternate" content="${OG_LOCALE[l]}">`),
    `<meta property="og:url" content="${url}">`,
    `<meta property="og:title" content="${escapeAttr(title)}">`,
    `<meta property="og:description" content="${escapeAttr(desc)}">`,
    `<meta property="og:image" content="${og}">`,
    `<meta property="og:image:secure_url" content="${og}">`,
    '<meta property="og:image:type" content="image/png">',
    '<meta property="og:image:width" content="1200">',
    '<meta property="og:image:height" content="630">',
    '<meta property="og:image:alt" content="negaflow for macOS with its film development workspace">',
    '<meta name="twitter:card" content="summary_large_image">',
    `<meta name="twitter:title" content="${escapeAttr(title)}">`,
    `<meta name="twitter:description" content="${escapeAttr(desc)}">`,
    `<meta name="twitter:image" content="${og}">`,
    '<meta name="twitter:image:alt" content="negaflow for macOS with its film development workspace">',
    '<script type="application/ld+json">',
    jsonLd(lang, dict, version),
    '</script>',
    HEAD_END
  ].join('\n');
}

/* ── page ─────────────────────────────────────────────────────────────── */

function buildPage(lang, template, dict, version) {
  let html = applyDict(template, dict[lang]);

  const head = buildHead(lang, dict[lang], version);
  const s = html.indexOf(HEAD_START);
  const e = html.indexOf(HEAD_END);
  if (s < 0 || e < 0) throw new Error('index.html is missing the nf:head markers');
  html = html.slice(0, s) + head + html.slice(e + HEAD_END.length);

  const sub = lang !== DEFAULT_LANG;
  const prefix = sub ? '../' : '';

  /* language menu points at the other prerendered pages */
  html = html.replace(/(<button role="option" data-lang="([a-z]+)")(?: data-href="[^"]*")?/g,
    (_, head_, l) => `${head_} data-href="${l === DEFAULT_LANG ? prefix || './' : prefix + l + '/'}"`);

  /* The root page keeps detecting the browser language, so a first-time
   * visitor still lands in their own language. The prerendered /<lang>/ pages
   * are locked: there the URL decides, which is what a crawler indexes. */
  const htmlTag = [
    `<html lang="${HREFLANG[lang]}"`,
    `data-theme="dark"`,
    `data-lang="${lang}"`,
    sub ? `data-lang-locked="1"` : null,
    `data-scheme="auto"`,
    sub ? `data-base="${prefix}"` : null
  ].filter(Boolean).join(' ') + '>';
  html = html.replace(/<html[^>]*>/, htmlTag);

  if (sub) {
    html = html.replace(/(["'(])assets\//g, `$1${prefix}assets/`);
  }

  return html;
}

/* ── sitemap and robots ───────────────────────────────────────────────── */

function buildSitemap() {
  const today = new Date().toISOString().slice(0, 10);
  const entries = LANGS.map((lang) => {
    const alts = LANGS
      .map((l) => `    <xhtml:link rel="alternate" hreflang="${HREFLANG[l]}" href="${pageUrl(l)}"/>`)
      .concat(`    <xhtml:link rel="alternate" hreflang="x-default" href="${pageUrl(DEFAULT_LANG)}"/>`)
      .join('\n');
    return [
      '  <url>',
      `    <loc>${pageUrl(lang)}</loc>`,
      alts,
      `    <lastmod>${today}</lastmod>`,
      `    <changefreq>weekly</changefreq>`,
      `    <priority>${lang === DEFAULT_LANG ? '1.0' : '0.9'}</priority>`,
      '  </url>'
    ].join('\n');
  }).join('\n');

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    entries,
    '</urlset>',
    ''
  ].join('\n');
}

function buildRobots() {
  return [
    'User-agent: *',
    'Allow: /',
    '',
    `Sitemap: ${SITE}/sitemap.xml`,
    ''
  ].join('\n');
}

/* ── run ──────────────────────────────────────────────────────────────── */

function emit(relPath, content) {
  const abs = join(ROOT, relPath);
  const current = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (current === content) return;
  if (check) {
    stale.push(relPath);
    return;
  }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
  written.push(relPath);
}

const dict = loadDict();
const template = readFileSync(join(ROOT, 'index.html'), 'utf8');

const version = (template.match(/negaflow-(\d+\.\d+\.\d+)-\d+-macOS-universal\.pkg/) || [])[1];
if (!version) throw new Error('could not read the version from the download section');

for (const lang of LANGS) {
  emit(lang === DEFAULT_LANG ? 'index.html' : `${lang}/index.html`,
    buildPage(lang, template, dict, version));
}
emit('sitemap.xml', buildSitemap());
emit('robots.txt', buildRobots());

if (check) {
  if (stale.length) {
    console.error('stale generated files — run `node tools/build.mjs`:');
    for (const f of stale) console.error('  ' + f);
    process.exit(1);
  }
  console.log(`generated files are up to date (negaflow ${version})`);
} else {
  console.log(written.length
    ? `wrote ${written.length} file(s) for negaflow ${version}:\n  ${written.join('\n  ')}`
    : `already up to date (negaflow ${version})`);
}
