/* negaflow site generator
 *
 * index.html is the template and, at the same time, the English page.
 * For every other language it writes a prerendered copy under /<lang>/ so that
 * search engines see real translated markup instead of text that only appears
 * after i18n.js runs.
 *
 *   node tools/build.mjs           write the generated files
 *   node tools/build.mjs --check   fail if the generated files are stale
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/* Change this one line when the site moves to its own domain. */
const ORIGIN = 'https://habinsong.github.io';
const BASE_PATH = '/negaflow-site';
const SITE = ORIGIN + BASE_PATH;

const DEFAULT_LANG = 'en';
const LANGS = ['en', 'ko', 'ja', 'zh', 'fr', 'de'];

/* Ownership tokens from the search consoles. Paste the value only — the part
 * inside content="…" — and leave a string empty to drop its tag.
 *   google  Google Search Console  https://search.google.com/search-console
 *   bing    Bing Webmaster Tools   https://www.bing.com/webmasters
 *   naver   네이버 서치어드바이저    https://searchadvisor.naver.com
 */
const VERIFICATION = {
  google: 'hLa4SvWRmd_iTnd1qb9w3E9SyO-LMpD-45kQEbdAcVU',
  bing: '',
  naver: ''
};

const HREFLANG = { en: 'en', ko: 'ko', ja: 'ja', zh: 'zh-Hans', fr: 'fr', de: 'de' };
const OG_LOCALE = { en: 'en_US', ko: 'ko_KR', ja: 'ja_JP', zh: 'zh_CN', fr: 'fr_FR', de: 'de_DE' };

const HEAD_START = '<!-- nf:head:start — generated by tools/build.mjs, do not edit by hand -->';
const HEAD_END = '<!-- nf:head:end -->';

/* Each topic gets its own URL so it can answer its own search.
 * `heading` and `desc` name existing i18n keys; a literal is used as written,
 * which is what the two engine names need. `sections` lists the section ids
 * lifted out of index.html, in order. `card` names the picture the page shows
 * when it is shared; without one it falls back to the app's own card. */
const TOPICS = [
  {
    slug: 'chroma-engine',
    heading: { literal: 'Chroma Engine' },
    desc: { key: 'chroma.lede' },
    sections: ['chroma', 'color-science'],
    card: 'chroma-engine.jpg'
  },
  {
    slug: 'grainmend',
    heading: { literal: 'GrainMend' },
    desc: { key: 'gm.lede' },
    sections: ['grainmend'],
    card: 'grainmend.jpg'
  },
  {
    slug: 'print-layouts',
    heading: { key: 'print.title' },
    desc: { key: 'print.lede' },
    sections: ['print'],
    card: 'print-layouts.jpg'
  },
  {
    slug: 'film-profiles',
    heading: { key: 'pr.title' },
    desc: { key: 'pr.lede' },
    sections: ['profiles'],
    card: 'film-profiles.jpg'
  },
  {
    slug: 'comparison',
    heading: { key: 'cmp.title' },
    desc: { key: 'cmp.lede' },
    sections: ['comparison', 'capture-methods'],
    card: 'comparison.jpg'
  },
  {
    slug: 'camera-scanning',
    heading: { key: 'cam.title' },
    desc: { key: 'cam.lede' },
    sections: ['camera-scanning'],
    card: 'chroma-engine.jpg'
  },
  {
    slug: 'how-to-invert-film-negatives',
    heading: { key: 'inv.title' },
    desc: { key: 'inv.lede' },
    sections: ['invert-guide'],
    card: 'comparison.jpg'
  },
  {
    slug: 'faq',
    heading: { key: 'faq.title' },
    desc: { key: 'faq.a1' },
    sections: ['faq']
  },
  {
    slug: 'download',
    heading: { key: 'dl.title' },
    desc: { key: 'dl.body' },
    sections: ['download'],
    card: 'download.jpg'
  }
];

const check = process.argv.includes('--check');
const written = [];
const stale = [];

/* ── i18n dictionary ──────────────────────────────────────────────────── */

function loadDict() {
  const src = readFileSync(join(ROOT, 'assets/js/i18n.js'), 'utf8');
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(src, sandbox, { filename: 'i18n.js' });
  const dict = sandbox.window.NF_I18N;
  if (!dict) throw new Error('i18n.js did not define window.NF_I18N');
  for (const lang of LANGS) {
    if (!dict[lang]) throw new Error(`i18n.js has no "${lang}" dictionary`);
  }
  return dict;
}

/* ── template rewriting ───────────────────────────────────────────────── */

const VOID = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
  'link', 'meta', 'param', 'source', 'track', 'wbr']);

/* End of the open tag that starts at `lt`, skipping `>` inside attributes. */
function openTagEnd(html, lt) {
  let quote = null;
  for (let i = lt + 1; i < html.length; i++) {
    const c = html[i];
    if (quote) {
      if (c === quote) quote = null;
    } else if (c === '"' || c === "'") {
      quote = c;
    } else if (c === '>') {
      return i;
    }
  }
  return -1;
}

/* Start of the matching close tag for an element of `name` opened at `from`. */
function closeTagStart(html, name, from) {
  const open = new RegExp(`<${name}(?=[\\s/>])`, 'gi');
  const close = new RegExp(`</${name}\\s*>`, 'gi');
  let depth = 1;
  let i = from;
  while (i < html.length) {
    open.lastIndex = i;
    close.lastIndex = i;
    const o = open.exec(html);
    const c = close.exec(html);
    if (!c) return -1;
    if (o && o.index < c.index) {
      depth++;
      i = o.index + o[0].length;
      continue;
    }
    depth--;
    if (depth === 0) return c.index;
    i = c.index + c[0].length;
  }
  return -1;
}

/* Alt text is an attribute, not markup, so it is translated on its own. Search
 * engines read it as the caption of the picture, once per language. */
function applyAltDict(html, dict) {
  return html.replace(/<img\b[^>]*\bdata-i18n-alt="([^"]+)"[^>]*>/g, (tag, key) => {
    const value = dict[key];
    if (value == null) return tag;
    const alt = ` alt="${escapeAttr(stripTags(value))}"`;
    /* index.html is the template and the English page at once, so this has to
     * land the same way whether or not the tag already carries an alt */
    return /\salt="[^"]*"/.test(tag)
      ? tag.replace(/\salt="[^"]*"/, alt)
      : tag.replace(/\s*\/?>$/, (end) => alt + end);
  });
}

/* Replace the inner markup of every [data-i18n] element with its translation. */
function applyDict(html, dict) {
  const attr = /data-i18n="([^"]+)"/g;
  const edits = [];
  let m;
  while ((m = attr.exec(html))) {
    const key = m[1];
    const value = dict[key];
    if (value == null) continue;

    const lt = html.lastIndexOf('<', m.index);
    if (lt < 0) continue;
    const name = (html.slice(lt + 1).match(/^[a-zA-Z][a-zA-Z0-9-]*/) || [])[0];
    if (!name || VOID.has(name.toLowerCase())) continue;

    const gt = openTagEnd(html, lt);
    if (gt < 0 || html[gt - 1] === '/') continue;
    const end = closeTagStart(html, name, gt + 1);
    if (end < 0) continue;

    edits.push({ start: gt + 1, end, value });
  }

  let out = html;
  for (const e of edits.reverse()) out = out.slice(0, e.start) + e.value + out.slice(e.end);
  return out;
}

function stripTags(s) {
  return String(s)
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&middot;/g, '·')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

function pageUrl(lang, slug) {
  const base = lang === DEFAULT_LANG ? `${SITE}/` : `${SITE}/${lang}/`;
  return slug ? `${base}${slug}/` : base;
}

/* How deep the page sits below the site root, as a relative prefix. */
function prefixFor(lang, slug) {
  return '../'.repeat((lang === DEFAULT_LANG ? 0 : 1) + (slug ? 1 : 0));
}

function textFor(source, dict) {
  return stripTags(source.literal != null ? source.literal : dict[source.key]);
}

/* Lift `<section id="…">…</section>` out of the page. */
function extractSection(html, id) {
  const open = new RegExp(`<section[^>]*\\bid="${id}"`, 'i');
  const m = open.exec(html);
  if (!m) throw new Error(`index.html has no section with id "${id}"`);
  const gt = openTagEnd(html, m.index);
  const end = closeTagStart(html, 'section', gt + 1);
  if (end < 0) throw new Error(`section "${id}" is not closed`);
  return html.slice(m.index, end + '</section>'.length);
}

/* ── structured data ──────────────────────────────────────────────────── */

function jsonLd(lang, dict, version, topic) {
  const app = {
    '@type': 'SoftwareApplication',
    '@id': `${SITE}/#app`,
    name: 'negaflow',
    url: pageUrl(lang),
    inLanguage: HREFLANG[lang],
    description: stripTags(dict['doc.desc']),
    applicationCategory: 'MultimediaApplication',
    applicationSubCategory: 'Photo editing',
    operatingSystem: 'macOS 14.0 or later',
    processorRequirements: 'Apple Silicon or Intel',
    softwareVersion: version,
    downloadUrl: 'https://github.com/habinsong/negaflow/releases',
    installUrl: 'https://github.com/habinsong/negaflow/releases',
    softwareHelp: 'https://github.com/habinsong/negaflow#readme',
    license: 'https://www.apache.org/licenses/LICENSE-2.0',
    isAccessibleForFree: true,
    image: `${SITE}/assets/og/default.jpg`,
    screenshot: `${SITE}/assets/og/default.jpg`,
    author: { '@type': 'Person', name: 'habin song', url: 'https://github.com/habinsong' },
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    featureList: [1, 2, 3, 4, 5, 6]
      .map((n) => dict[`feat.${n}`])
      .filter(Boolean)
      .map(stripTags)
  };

  if (topic) {
    return JSON.stringify({
      '@context': 'https://schema.org',
      '@graph': [
        app,
        {
          '@type': 'BreadcrumbList',
          itemListElement: [
            {
              '@type': 'ListItem',
              position: 1,
              name: 'negaflow',
              item: pageUrl(lang)
            },
            {
              '@type': 'ListItem',
              position: 2,
              name: textFor(topic.heading, dict),
              item: pageUrl(lang, topic.slug)
            }
          ]
        }
      ]
    }, null, 2);
  }

  const faq = [];
  for (let n = 1; n <= 20; n++) {
    const q = dict[`faq.q${n}`];
    const a = dict[`faq.a${n}`];
    if (!q || !a) continue;
    faq.push({
      '@type': 'Question',
      name: stripTags(q),
      acceptedAnswer: { '@type': 'Answer', text: stripTags(a) }
    });
  }

  const graph = [app];
  if (faq.length) {
    graph.push({
      '@type': 'FAQPage',
      '@id': `${pageUrl(lang)}#faq`,
      inLanguage: HREFLANG[lang],
      mainEntity: faq
    });
  }

  return JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 2);
}

/* ── head ─────────────────────────────────────────────────────────────── */

function escapeAttr(s) {
  return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

function buildHead(lang, dict, version, topic) {
  const slug = topic ? topic.slug : null;
  const title = topic
    ? `${textFor(topic.heading, dict)} — negaflow`
    : stripTags(dict['doc.title']);
  const desc = topic ? textFor(topic.desc, dict) : stripTags(dict['doc.desc']);
  const url = pageUrl(lang, slug);
  const og = `${SITE}/assets/og/${topic && topic.card ? topic.card : 'default.jpg'}`;

  const alternates = LANGS
    .map((l) => `<link rel="alternate" hreflang="${HREFLANG[l]}" href="${pageUrl(l, slug)}">`)
    .concat(`<link rel="alternate" hreflang="x-default" href="${pageUrl(DEFAULT_LANG, slug)}">`)
    .join('\n');

  return [
    HEAD_START,
    `<title>${escapeAttr(title)}</title>`,
    `<meta name="description" content="${escapeAttr(desc)}">`,
    '<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">',
    ...(VERIFICATION.google
      ? [`<meta name="google-site-verification" content="${escapeAttr(VERIFICATION.google)}">`] : []),
    ...(VERIFICATION.bing
      ? [`<meta name="msvalidate.01" content="${escapeAttr(VERIFICATION.bing)}">`] : []),
    ...(VERIFICATION.naver
      ? [`<meta name="naver-site-verification" content="${escapeAttr(VERIFICATION.naver)}">`] : []),
    `<link rel="canonical" href="${url}">`,
    alternates,
    '<meta property="og:type" content="website">',
    '<meta property="og:site_name" content="negaflow">',
    `<meta property="og:locale" content="${OG_LOCALE[lang]}">`,
    ...LANGS.filter((l) => l !== lang)
      .map((l) => `<meta property="og:locale:alternate" content="${OG_LOCALE[l]}">`),
    `<meta property="og:url" content="${url}">`,
    `<meta property="og:title" content="${escapeAttr(title)}">`,
    `<meta property="og:description" content="${escapeAttr(desc)}">`,
    `<meta property="og:image" content="${og}">`,
    `<meta property="og:image:secure_url" content="${og}">`,
    '<meta property="og:image:type" content="image/jpeg">',
    '<meta property="og:image:width" content="1200">',
    '<meta property="og:image:height" content="630">',
    '<meta property="og:image:alt" content="negaflow for macOS with its film development workspace">',
    '<meta name="twitter:card" content="summary_large_image">',
    `<meta name="twitter:title" content="${escapeAttr(title)}">`,
    `<meta name="twitter:description" content="${escapeAttr(desc)}">`,
    `<meta name="twitter:image" content="${og}">`,
    '<meta name="twitter:image:alt" content="negaflow for macOS with its film development workspace">',
    '<script type="application/ld+json">',
    jsonLd(lang, dict, version, topic),
    '</script>',
    HEAD_END
  ].join('\n');
}

/* ── page ─────────────────────────────────────────────────────────────── */

function buildPage(lang, template, dict, version, topic) {
  const d = dict[lang];
  const slug = topic ? topic.slug : null;
  const prefix = prefixFor(lang, slug);
  /* the overview page of this language, relative to the page being written */
  const home = prefix + (lang === DEFAULT_LANG ? '' : lang + '/');

  let html = applyAltDict(applyDict(template, d), d);

  if (topic) {
    const body = topic.sections
      .map((id) => extractSection(html, id))
      /* the section heading becomes the heading of the page it now owns */
      .map((s, i) => (i === 0 ? s.replace(/<h2( [^>]*)?>/, '<h1$1>').replace(/<\/h2>/, '</h1>') : s))
      .join('\n\n');

    /* no back link: the brand in the bar already goes to the overview */
    html = html.replace(/<main id="main">[\s\S]*<\/main>/,
      `<main id="main">\n  <span id="top"></span>\n\n${body}\n</main>`);
    html = html.replace('<body>', '<body class="topic-page">');
  }

  const head = buildHead(lang, d, version, topic);
  const s = html.indexOf(HEAD_START);
  const e = html.indexOf(HEAD_END);
  if (s < 0 || e < 0) throw new Error('index.html is missing the nf:head markers');
  html = html.slice(0, s) + head + html.slice(e + HEAD_END.length);

  /* language menu points at the same page in the other languages */
  html = html.replace(/(<button role="option" data-lang="([a-z]+)")(?: data-href="[^"]*")?/g,
    (_, open, l) => {
      const path = (l === DEFAULT_LANG ? '' : l + '/') + (slug ? slug + '/' : '');
      return `${open} data-href="${prefix + path || './'}"`;
    });

  /* Every link that names a page carries data-path, written relative to the
   * site root. That one attribute resolves here for the generated pages and
   * again in app.js when the root page switches language. */
  const dir = lang === DEFAULT_LANG ? '' : lang + '/';
  html = html.replace(/<a([^>]*\bdata-path="([^"]*)"[^>]*)>/g, (_, attrs, path) => {
    const clean = attrs.replace(/\s+href="[^"]*"/g, '').replace(/\s+aria-current="[^"]*"/g, '');
    const href = prefix + dir + path || './';
    const here = slug && path === `${slug}/` ? ' aria-current="page"' : '';
    return `<a href="${href}"${clean}${here}>`;
  });

  /* The root page keeps detecting the browser language, so a first-time
   * visitor still lands in their own language. Every generated page is
   * locked: there the URL decides, which is what a crawler indexes. */
  const locked = lang !== DEFAULT_LANG || !!topic;
  const htmlTag = [
    `<html lang="${HREFLANG[lang]}"`,
    `data-theme="dark"`,
    `data-lang="${lang}"`,
    locked ? `data-lang-locked="1"` : null,
    `data-scheme="auto"`,
    prefix ? `data-base="${prefix}"` : null
  ].filter(Boolean).join(' ') + '>';
  html = html.replace(/<html[^>]*>/, htmlTag);

  if (prefix) {
    html = html.replace(/(["'(])assets\//g, `$1${prefix}assets/`);
  }

  if (topic) {
    /* any in-page anchor left over belongs to the overview */
    html = html.replace(/href="#(?!main\b)([\w-]+)"/g, `href="${home || './'}#$1"`);
    /* and a section does not link to the page it is already on */
    html = html.replace(/[ \t]*<p class="topic-more[^>]*>[\s\S]*?<\/p>\n?/g, '');
  }

  return html;
}

/* ── sitemap and robots ───────────────────────────────────────────────── */

function buildSitemap() {
  const slugs = [null, ...TOPICS.map((t) => t.slug)];
  const entries = slugs.flatMap((slug) => LANGS.map((lang) => {
    const dir = lang === DEFAULT_LANG ? '' : `${lang}/`;
    const alts = LANGS
      .map((l) => `    <xhtml:link rel="alternate" hreflang="${HREFLANG[l]}" href="${pageUrl(l, slug)}"/>`)
      .concat(`    <xhtml:link rel="alternate" hreflang="x-default" href="${pageUrl(DEFAULT_LANG, slug)}"/>`)
      .join('\n');
    const priority = slug ? '0.7' : (lang === DEFAULT_LANG ? '1.0' : '0.9');
    return [
      '  <url>',
      `    <loc>${pageUrl(lang, slug)}</loc>`,
      alts,
      `    <lastmod>${lastmodFor(`${dir}${slug ? slug + '/' : ''}index.html`)}</lastmod>`,
      `    <changefreq>weekly</changefreq>`,
      `    <priority>${priority}</priority>`,
      '  </url>'
    ].join('\n');
  })).join('\n');

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    entries,
    '</urlset>',
    ''
  ].join('\n');
}

function buildRobots() {
  return [
    'User-agent: *',
    'Allow: /',
    '',
    `Sitemap: ${SITE}/sitemap.xml`,
    ''
  ].join('\n');
}

/* ── run ──────────────────────────────────────────────────────────────── */

/*
 * A crawler reads <lastmod> as "this page changed on that day", so stamping
 * every page with the build date on every build turns the whole sitemap into
 * noise. The dates live in tools/lastmod.json and only the pages whose markup
 * actually came out different are moved to today.
 */
const LASTMOD_FILE = 'tools/lastmod.json';
const TODAY = new Date().toISOString().slice(0, 10);

let lastmod = {};
try {
  lastmod = JSON.parse(readFileSync(join(ROOT, LASTMOD_FILE), 'utf8'));
} catch {
  lastmod = {};
}

function lastmodFor(relPath) {
  return lastmod[relPath] || TODAY;
}

function emit(relPath, content) {
  const abs = join(ROOT, relPath);
  const current = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (current === content) {
    if (relPath.endsWith('index.html') && !lastmod[relPath]) lastmod[relPath] = TODAY;
    return;
  }
  if (relPath.endsWith('index.html')) lastmod[relPath] = TODAY;
  if (check) {
    stale.push(relPath);
    return;
  }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
  written.push(relPath);
}

const dict = loadDict();
const template = readFileSync(join(ROOT, 'index.html'), 'utf8');

const version = (template.match(/negaflow-(\d+\.\d+\.\d+)-\d+-macOS-universal\.pkg/) || [])[1];
if (!version) throw new Error('could not read the version from the download section');

for (const lang of LANGS) {
  const dir = lang === DEFAULT_LANG ? '' : `${lang}/`;
  emit(`${dir}index.html`, buildPage(lang, template, dict, version));
  for (const topic of TOPICS) {
    emit(`${dir}${topic.slug}/index.html`, buildPage(lang, template, dict, version, topic));
  }
}
emit('sitemap.xml', buildSitemap());
emit('robots.txt', buildRobots());

if (!check) {
  const sorted = {};
  for (const key of Object.keys(lastmod).sort()) sorted[key] = lastmod[key];
  writeFileSync(join(ROOT, LASTMOD_FILE), JSON.stringify(sorted, null, 2) + '\n');
}

if (check) {
  if (stale.length) {
    console.error('stale generated files — run `node tools/build.mjs`:');
    for (const f of stale) console.error('  ' + f);
    process.exit(1);
  }
  console.log(`generated files are up to date (negaflow ${version})`);
} else {
  console.log(written.length
    ? `wrote ${written.length} file(s) for negaflow ${version}:\n  ${written.join('\n  ')}`
    : `already up to date (negaflow ${version})`);
}
